### PR TITLE
Catch share cancellation

### LINKED ISSUE #98: Canceling the share button throws
### What happened?

If you cancel sharing, it throws with:

```
Abort due to cancellation of share.
      
Microsoft.JSInterop.JSException: Abort due to cancellation of share.

   at Microsoft.JSInterop.JSRuntime.<InvokeAsync>d__16`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at Prolangle.Components.ShareCodeSnippetButton.OnClicked()
```

### What browsers are you seeing the problem on?

Safari

### Relevant log output

_No response_

### Screenshots

_No response_

### PR DESCRIPTION
**Pull request by chucker**
Fixes #98

I'm wrapping it in a try/catch and logging it as a warning. I don't think there's anything critical that could happen in a share sheet.

### CODE REVIEW

File: Prolangle/wwwroot/js/app.js [hunk 1]
```diff
@@ -25,7 +25,11 @@ async function shareResult(text) {
         return "Result copied to clipboard.";
     }
 
-    await navigator.share(shareData);
+    try {
+        await navigator.share(shareData);
+    } catch (e) {
+        console.warn(`Error occurred during share sheet: ${e}`);
```
Comment (ricardoboss) [inline Prolangle/wwwroot/js/app.js:31]:
```suggestion
        console.warn('Error occurred during share sheet: ', e);
```

This way the JS console can render whatever the value is in a rich way as opposed to converting it to a string first.
