### PR TITLE
Added typescript (and fixed JS name)

### LINKED ISSUE #124: Typescript

### PR DESCRIPTION
**Pull request by ricardoboss**
Fixes #124

### CODE REVIEW

File: Prolangle/Languages/TypeScript.cs [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+
+	public override Guid Id { get; } = Guid.NewGuid();
+	public override string Name => "TypeScript";
+	public override TypeSystem Typing => TypeSystem.Duck | TypeSystem.Structural | TypeSystem.Strong | TypeSystem.Static;
+	public override bool Compiled => true;
+	public override MemoryManagement MemoryManagement => MemoryManagement.TracingGarbageCollection;
+	public override SyntaxStyle SyntaxStyle => SyntaxStyle.C;
+
+	public override Applications KnownForBuilding =>
+		Applications.Client | Applications.Configuration |
```
Comment (chucker) [inline Prolangle/Languages/TypeScript.cs:21]: I question `Configuration` (within the TS ecosystem, _I guess_, but outside of that?) and `Scripts` (do OSes ship with it? Does it even work without compiling to a different file?)

File: Prolangle/Languages/TypeScript.cs [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+		Applications.Server | Applications.Web |
+		Applications.Scripts;
+
+	public override Paradigms Paradigms =>
+		Paradigms.EventDriven | Paradigms.Functional | Paradigms.Imperative |
+		Paradigms.Procedural | Paradigms.ObjectOriented | Paradigms.Generic;
```
Comment (chucker) [inline Prolangle/Languages/TypeScript.cs:27]: I vaguely recall that we didn't want to call a language `Procedural` and/or `Imperative` if it's also `ObjectOriented` (because otherwise, aren't _all_ OOP languages P and I?), but unsure

**Review by chucker — CHANGES_REQUESTED** [review]

File: Prolangle/Languages/TypeScript.cs (hunk 1 above)
Comment (ricardoboss) [reply Prolangle/Languages/TypeScript.cs:21]: Deno can run TS files directly. But it's not widely used yet...

File: Prolangle/Languages/TypeScript.cs [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+	public override bool Compiled => true;
+	public override MemoryManagement MemoryManagement => MemoryManagement.TracingGarbageCollection;
+	public override SyntaxStyle SyntaxStyle => SyntaxStyle.C;
+
+	public override Applications KnownForBuilding => Applications.Client | Applications.Server | Applications.Web;
+
+	public override Paradigms Paradigms =>
+		Paradigms.EventDriven | Paradigms.Functional | Paradigms.ObjectOriented | Paradigms.Generic;
+
+	public override double? TiobeRating => 0.37;
```
Comment (chucker) [inline Prolangle/Languages/TypeScript.cs:25]: FWIW, it's `0.23` now. But I don't think it's worth chasing these metrics over time _too much_.

**Review by chucker — APPROVED** [review]
